on:
  workflow_dispatch:

jobs:
  run:
    runs-on: "ubuntu-latest"
    
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
    
      - name: Install mip_matching
        run: |
          cd algorithm
          python -m pip install -e .

      - name: Install pymongo
        run: |
          cd algorithm
          python -m pip install pymongo[srv]

      - name: Run tests
        run: |
          cd algorithm
          python bridge/fetch_applicants_and_committees.py
